# COURSE: A deep understanding of deep learning
## SECTION: Data matrices and loaders
### LECTURE: Anatomy of a torch dataset and dataloader
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202201

In [1]:
# import libraries
import numpy as np
import torch
from torch.utils.data import DataLoader,TensorDataset

# Datasets

In [2]:
# create some data in numpy

nObservations = 100
nFeatures = 20

data = np.random.randn(nObservations,nFeatures)

In [3]:
# Convert to pytorch tensor
dataT = torch.tensor( data ) 

# print out some information
print('Numpy data:')
print(type(data))
print(data.shape) # numpy -> .shape
print(data.dtype)
print(' ')

print('Tensor data:')
print(type(dataT))
print(dataT.size()) # torch -> .size()
print(dataT.dtype)
print(' ')

Numpy data:
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data:
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [4]:
# Sometimes you need to convert data types

dataT2 = torch.tensor( data ).float()
print(dataT2.dtype)

# "long" is for ints
dataT3 = torch.tensor( data ).long()
print(dataT3.dtype)


torch.float32
torch.int64


In [14]:
# Convert tensor into PyTorch Datasets

# dataset = TensorDataset(data) # not a tensor!
dataset = TensorDataset(dataT)

# dataset is a two-element tuple comprising data,labels
dataset.tensors[0]

tensor([[ 0.2128, -0.9342, -1.6988,  ..., -2.0021, -1.7738,  1.6852],
        [ 0.4719, -0.5193, -2.1423,  ..., -2.1411, -0.3065, -0.5517],
        [ 1.3608, -0.0274,  0.0956,  ...,  0.6149,  0.2322,  1.2600],
        ...,
        [-0.0526, -1.4244,  0.5263,  ..., -0.6099,  2.0615, -0.4766],
        [-0.6390,  0.3112,  0.3059,  ...,  0.1478,  1.1062, -0.3235],
        [-0.5892, -2.8908,  0.3124,  ..., -0.1328, -0.2685,  0.2341]],
       dtype=torch.float64)

In [16]:
# Let's try again with labels
labels = torch.ceil(torch.linspace(.01,4,nObservations))

# transform to an actual matrix (column vector)
labels = labels.reshape(( len(labels),1 ))
# print( labels )

# now make another dataset
dataset = TensorDataset(dataT,labels)
print( dataset.tensors[0].size() )
print( dataset.tensors[1].size() )

# for comparison
print( np.shape(np.random.randint(5,size=nObservations)) )

torch.Size([100, 20])
torch.Size([100, 1])
(100,)


# DataLoaders

In [25]:
# create a dataloader object
batchsize = 25
dataloader = DataLoader(dataset, batch_size=batchsize, shuffle=True, drop_last=True)

dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [26]:
# sizes of each batch
for dat,labs in dataloader:
  print('BATCH INFO:')
  print(dat.size())
  print(labs.size())
  print(' ')

BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [37]:
# inspect the labels
for dat,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[1., 2., 4., 1., 4., 3., 3., 2., 1., 2., 2., 3., 1., 2., 1., 4., 2., 2.,
         3., 2., 4., 4., 1., 1., 1.]])
 
tensor([[3., 4., 1., 2., 1., 4., 3., 1., 1., 3., 2., 4., 1., 3., 4., 2., 3., 3.,
         2., 3., 3., 1., 4., 3., 2.]])
 
tensor([[4., 4., 1., 4., 4., 2., 3., 3., 2., 2., 2., 3., 4., 2., 3., 4., 4., 3.,
         4., 1., 1., 1., 1., 3., 1.]])
 
tensor([[1., 2., 1., 4., 1., 3., 4., 3., 4., 3., 4., 2., 2., 4., 1., 1., 2., 3.,
         4., 2., 3., 3., 4., 2., 2.]])
 


In [ ]:
# try again with shuffling (shuffling happens during iterations)
# dataloader = DataLoader(dataset,batch_size=batchsize,shuffle=True)

for dat,labs in dataloader:
  print(labs.T)
  print(' ')

In [ ]:
# To get only one batch (e.g., for testing)

dat,labs = next(iter(dataloader))

labs