# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202201

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


# Peeking inside the network

In [3]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[-0.5488, -0.5924],
        [-0.5127,  0.1778]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.2855, -0.2244], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.1269,  0.0526],
        [ 0.5130,  0.0246]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([ 0.4568, -0.3204], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.0254,  0.5472],
        [-0.5564, -0.4586],
        [ 0.4857, -0.5670]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.2780, -0.1718, -0.1315], requires_grad=True))
 


In [4]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [5]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.6829, -0.0679],
        [ 0.4069, -0.2105],
        [-0.3033, -0.5680],
        [-0.2126, -0.4870]], requires_grad=True)
 
Parameter containing:
tensor([-0.4228,  0.4227,  0.4511,  0.5664], requires_grad=True)
 
Parameter containing:
tensor([[-0.2831,  0.2277,  0.3655, -0.4053],
        [-0.1616, -0.4611, -0.0517, -0.4438],
        [ 0.2031, -0.4604, -0.3174,  0.1221]], requires_grad=True)
 
Parameter containing:
tensor([-0.1967, -0.3377,  0.0282], requires_grad=True)
 


In [6]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [7]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [14]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)