# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202201

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.01  3.91 -2.44 -0.2   2.78]
 [-1.4   0.55  1.17 -0.56 -0.86]
 [-1.01  6.1  -5.22 -2.78  6.25]]
 
[[-4.01  1.97  4.07  0.79]
 [ 0.    0.68  0.27 -3.73]
 [-0.74 -0.25 -0.69  2.74]
 [ 3.83 -1.9  -1.65  0.73]
 [-2.35  1.71  4.98 -1.12]
 [ 1.86 -1.18 -2.21  0.95]
 [ 2.08 -1.03 -1.7  -0.11]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[-2.1100, -0.2600, -0.8200, -4.8000,  3.1700, -1.5700, -4.3300],
        [-0.0500, -1.8400, -0.3100, -1.5000,  1.3800, -2.2900, -1.5900],
        [-0.7100,  0.7100,  0.2400, -1.3700,  0.0400,  0.8100, -1.4500]],
       dtype=torch.float64)
 
tensor([[-2.1100, -0.2600, -0.8200, -4.8000,  3.1700, -1.5700, -4.3300],
        [-0.0500, -1.8400, -0.3100, -1.5000,  1.3800, -2.2900, -1.5900],
        [-0.7100,  0.7100,  0.2400, -1.3700,  0.0400,  0.8100, -1.4500]])
